
# services:
#   mongodb:
#     container_name: mongo_container
#     image: mongo:8.0.3
#     env_file:
#       - path: ../.dev.env
#     volumes:
#       - /mongodb
#     environment:
#       - MONGODB_URL=${MONGODB_URL}
#       - MONGODB_NAME=${MONGODB_NAME}
#       - MONGODB_SECRET=${MONGODB_SECRET}
#     ports:
#       - ${MONGODB_PORT}:${MONGODB_PORT}
#     networks:
#       - netnet
