# version: "3.8"
# services:
#   postgres:
#     container_name: pg_container
#     image: postgres:16.1-alpine3.19
#     env_file:
#       - ../.env.develop
#     volumes:
#       - /postgres
#     environment:
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_PORT=${POSTGRES_PORT}
#     ports:
#       - ${POSTGRES_PORT}:${POSTGRES_PORT}
#     networks:
#       - netnet